name: Terraform Azure Infrastructure

on:
  push:
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      TF_VAR_sql_admin_password: ${{ secrets.SQL_ADMIN_PASSWORD }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:

      # -------------------------------
      # Checkout Repository
      # -------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4


      # -------------------------------
      # Setup Terraform
      # -------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      # -------------------------------
      # Terraform Format Check
      # -------------------------------
      - name: Terraform Format Check
        run: terraform fmt -check -recursive


      # -------------------------------
      # Terraform Init
      # -------------------------------
      - name: Terraform Init
        run: terraform init


      # -------------------------------
      # Terraform Validate
      # -------------------------------
      - name: Terraform Validate
        run: terraform validate


      # -------------------------------
      # Terraform Plan
      # -------------------------------
      - name: Terraform Plan
        run: terraform plan -out=tfplan


      # -------------------------------
      # Terraform Apply
      # -------------------------------
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan